/*
 * ErrorFrame.java
 *
 * Created on February 3, 2001, 5:58 PM
 */

package jThergas.exceptions;

/**
 *
 * @author  reaction
 * @version 1.0
 */
public class ErrorFrame extends javax.swing.JFrame {

    /** Creates new form ErrorFrame */
    public ErrorFrame() {
        initComponents ();
        pack ();
    }
    public ErrorFrame(String text) {
        initComponents ();
        errorText.setText(text);
        pack ();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        errorText = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        dismissButton = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel2.setBorder(new javax.swing.border.TitledBorder("Message"));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(400, 200));
        errorText.setColumns(500);
        errorText.setRows(200);
        jScrollPane1.setViewportView(errorText);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel1.setLayout(new java.awt.GridLayout(1, 1));

        dismissButton.setText("Dismiss");
        dismissButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dismissFrame(evt);
            }
        });

        jPanel1.add(dismissButton);

        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

    }//GEN-END:initComponents

  private void dismissFrame(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dismissFrame
// Add your handling code here:
      doClose();
  }//GEN-LAST:event_dismissFrame

    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit (0);
    }//GEN-LAST:event_exitForm
    private void doClose () {
        setVisible (false);
        dispose ();
    }

    /**
    * @param args the command line arguments
    */
    public static void main (String args[]) {
        new ErrorFrame ().show ();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton dismissButton;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JTextArea errorText;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
